### ISSUE TITLE
Clean output option

### ISSUE THREAD

**Issue by Xylopyrographer** [ultimateanu/hashdir#17]
Hats off and thanks for this handy utility 👏🏻.

Could I request addition of an option that produces only the hash without the directory appended?

Right now I get, for example, this output:

`f3204e77fa886c346f338d813af766d0  /MyDir`

Would like the new option to produce only:

`f3204e77fa886c346f338d813af766d0`

Ail the best.

**Comment by ultimateanu** [comment]
There is now a `--hash-only` that does this in v1.2.0!

You can run one of the following commands to upgrade:
- `brew upgrade ultimateanu/software/hashdir`
- `dotnet tool update --global hashdir`
