### ISSUE TITLE
Skip Folders Only Hash Files

### ISSUE THREAD

**Issue by unstatusthequo** [ultimateanu/hashdir#19]
Is there a switch that will avoid hashing folders? Or, is the hash function literally hashing only the folder itself and _not all of the contents together?_

**Comment by unstatusthequo** [comment]
Yes my question was can it hash *only* files on an individual (children) basis of the folders/sub folders and not as a hash of the entire folder contents (many files hashed *together*) as a group.

Like this:

folder — don’t care about hash; don’t return hash value
|___file1.txt — hash this and return hash value
|___file1.txt — hash this and return hash value

**Comment by ultimateanu** [comment]
Yes, you can use the flag `--tree` or `-t` to output the individual hashes. Note that this still outputs the directory hash, but if you don't care about it you can just ignore it. Example:

```
> hashdir --tree folder/
f34f126f657e2df70dcf0962eb0aeba6f0d077a9  /folder                              
├── c7059bb19433cc3cabaa6236c83d56668a843dd2  file1.txt
└── 7bbef45b3bc70855010e02460717643125c3beca  file2.txt
```

If for some reason you want to avoid printing the directory hash, you can just hash the indivividual items. For example:
```
> hashdir folder/*
c7059bb19433cc3cabaa6236c83d56668a843dd2  file1.txt                            
7bbef45b3bc70855010e02460717643125c3beca  file2.txt
```

**Comment by unstatusthequo** [comment]
Excellent, that makes sense. Truly appreciate the responses.
