### ISSUE TITLE
Option to skip certain folders

### ISSUE THREAD

**Issue by Jumziey** [ultimateanu/hashdir#20]
Love the application

Only question would be if it's possible to add an option where you can skip a folder, i.e. node_modules etc.

**Comment by ultimateanu** [comment]
that is a great idea! Will scope it out a bit and incorporate it soon

**Comment by ultimateanu** [comment]
There is now a new flag to skip a folder or file: `--ignore`!

A few things to note:
1) The pattern specified will consider the target directory the root. So `hashdir --ignore "node_modules" ~/Desktop/project` will only ignore `~/Desktop/project/node_modules`.
2) If you wish to ignore all occurrences of something, use the standard globing pattern "**". So `hashdir --ignore "**/node_modules" ~/Desktop/project` will ignore all directories (& files) named `node_modules`.
3) You can specify custom patterns as needed using glob patterns (e.g. "build/cache", "output/temp/*.xml")
4) Lastly, you can specify multiple ignore patterns. `hashdir --ignore "node_modules" --ignore "**/*.xml" ~/Desktop/project`

Hope this helps!

**Comment by Jumziey** [comment]
This is great! Thank you :D can't wait to get going with this ^^
