### ISSUE TITLE
Create a single hash for all items?

### ISSUE THREAD

**Issue by Xylopyrographer** [ultimateanu/hashdir#23]
Is there a way to create a single combined hash for all `<items>` on the command line?

For example make :
    `hashdir -a md5 song.mp3 info.txt report.pdf`

output something like:
    `a01c1ff19134af2c36bd743b1c356c6fad2b751c /<all items>`

instead of:
    `c5932e4bb94655a54c57146be037bcc5d073fe77  song.mp3 info.txt`                                                                                                     
    `4a667049e9149508c765be2b92f0edcbcea7e251  report.pdf`

If not, could I ask this feature be considered in a future release?

Use case: I'm using PlatformIO for microcontroller development. I want a hash of only all the source code files for the project. However PlatformIO requires or puts source files in a number of directories. Along with other files that may be part of the project, quite a few files and folders exist at the project root level. I use (the end six chars) of the hash of just the source files as the software build number, so an easy way to create a combined hash of folders specified the command line would be very useful.

Thanks.

**Comment by ultimateanu** [comment]
I prefer to avoid too many options to the tool, which might over complicate it.

It seems you want a single hash for multiple items. I would suggest something like the following:
`hashdir song.mp3 info.txt report.pdf | shasum | head -c 6`

This should achieve your goal since we are using cryptographic hash functions. So taking a hash of the output should work.

**Comment by Xylopyrographer** [comment]
Sounds good. Thanks for the hint.

On May 9, 2023, at 4:20 PM, Anu Bandi ***@***.***> wrote:


I prefer to avoid too many options to the tool, which might over complicate it.

It seems you want a single hash for multiple items. I would suggest something like the following:
hashdir song.mp3 info.txt report.pdf | shasum | head -c 6

This should achieve your goal since we are using cryptographic hash functions. So taking a hash of the output should work.
