### ISSUE TITLE
Add scoop installation for Windows

### ISSUE THREAD

**Issue by Theramar** [ultimateanu/hashdir#24]
[scoop](https://scoop.sh/)

**Comment by ultimateanu** [comment]
Great idea, you should now be able to install via Scoop! Note that this project does not yet meet the requirements to be in the main bucket, so you will have to add a custom bucket and then install like so:

```
scoop bucket add ultimateanu https://github.com/ultimateanu/homebrew-software
scoop install hashdir
scoop update hashdir
```
